openapi: 3.0.3
info:
  title: Swagger Reserva Restaurante - Avaliações
  description: |-
    Api para cadastrar avaliações dos Restaurantes reservados - FIAP Fase 3 Tech Challenge
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost:8080
    description: Local server

tags:
  - name: Usuario
    description: Tudo sobre usuários

paths:
  /usuario/novo:
    post:
      tags:
        - Usuario
      summary: Adiciona um novo usuário
      description: Adiciona um novo usuário
      operationId: cadastrarUsuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastrarUsuario'
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          description: Entrada inválida
        '422':
          description: Exceção de validação
  /usuario/{id}:
    get:
      tags:
        - Usuario
      summary: Busca usuário por ID
      description: Busca um usuário pelo seu ID.
      operationId: buscarUsuarioPorId
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: ID do usuário
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '404':
          description: Usuário não encontrado

components:
    schemas:
        Usuario:
          type: object
          properties:
            id:
              type: string
              format: uuid
              description: ID do usuário.
              example: 123e4567-e89b-12d3-a456-426614174000
            nome:
              type: string
              example: João
            email:
              pattern: "O e-mail fornecido não está no formato correto. Por favor, insira um e-mail válido, como exemplo@dominio.com."
              type: string
              example: joao@teste.com

        CadastrarUsuario:
          type: object
          properties:
              nome:
                type: string
                example: João
              email:
                pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
                type: string
                example: joao@teste.com
              senha:
                type: string
                example: 123456